#DataSource Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hoaxify
    username: username
    password: password

  jpa:
    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update

